stages:
  - update-version
  - slack-push
  - code-quality
  - code-test
  - application-build
  - code-analysis
  - site-report
  - image-build
  - component-test
  - container-image-test
  - image-push
  - update-project-metadata
  - pages
  - open-source
  - create-schedules
